name = "verse-radar-updater"
main = "worker/index.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public/"

[triggers]
crons = ["0 */2 * * *"]

[vars]
GITHUB_REPO = "DEIN-GITHUB-USERNAME/verse-radar"
GITHUB_BRANCH = "main"
