import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";

const source = await readFile(new URL("../worker/index.js", import.meta.url), "utf8");
const worker = (await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`)).default;
const path = "public/data/deals.json";
const catalogPath = "public/data/ship-images.json";
let deals = [], sha = "deals-sha-1", writes = 0, shipImages = [], catalogSha = null, catalogWrites = 0;
globalThis.fetch = async (target, options = {}) => {
  if (String(target).includes(`/contents/${catalogPath}`)) {
    if (options.method === "PUT") {
      assert.equal(JSON.parse(options.body).sha, catalogSha || undefined);
      shipImages = JSON.parse(Buffer.from(JSON.parse(options.body).content, "base64").toString());
      catalogSha = `catalog-sha-${++catalogWrites}`;
      return Response.json({ content: { sha: catalogSha } });
    }
    if (!catalogSha) return Response.json({ message: "Not Found" }, { status: 404 });
    return Response.json({ sha: catalogSha, content: Buffer.from(JSON.stringify(shipImages)).toString("base64") });
  }
  if (!String(target).includes(`/contents/${path}`)) throw Error(`Unexpected URL: ${target}`);
  if (options.method === "PUT") {
    assert.equal(JSON.parse(options.body).sha, sha);
    deals = JSON.parse(Buffer.from(JSON.parse(options.body).content, "base64").toString());
    sha = `sha-${++writes}`;
    return Response.json({ content: { sha } });
  }
  return Response.json({ sha, content: Buffer.from(JSON.stringify(deals)).toString("base64") });
};
const env = { RUN_SECRET: "private", GITHUB_TOKEN: "github-key", GITHUB_REPO: "example/repo", GITHUB_BRANCH: "main" };
const request = (path, body, key = "private") => new Request(`https://example.com${path}`, { method: body ? "POST" : "GET", headers: { "x-run-secret": key, origin: "https://example.com" }, body: body ? JSON.stringify(body) : undefined });
const shop = "https://robertsspaceindustries.com/pledge/Packages/Test-Game-Package";
const future = "2030-10-01T12:00:00.000Z";
const picture = "https://media.robertsspaceindustries.com/package/aurora.jpg?size=large";
const proposal = { action: "set", data: { name: "Test Game Package", type: "Game Package", sourceUrl: shop, imageUrl: picture, saveImageToCatalog: true, price: "58,24", oldPrice: "77,65", currency: "EUR", referralEligible: "yes", ship: "Aurora", gameAccessConfirmed: true, extras: "3 Monate Versicherung\nSkin Blau", validUntil: future, note: "Manuell geprüft." } };

assert.equal((await worker.fetch(new Request("https://example.com/manage/deals/state"), env)).status, 401);
const page = await worker.fetch(new Request("https://example.com/manage/deals"), env);
assert.equal(page.status, 200);
assert.equal(await page.text(), await readFile(new URL("../public/deal-admin.html", import.meta.url), "utf8"));
assert.match(page.headers.get("content-security-policy"), /img-src https:\/\/robertsspaceindustries\.com https:\/\/\*\.robertsspaceindustries\.com/);
assert.equal((await (await worker.fetch(request("/manage/deals/state"), env)).json()).deals.length, 0);
assert.equal((await (await worker.fetch(request("/manage/deals/state"), env)).json()).shipImages.length, 0);
assert.equal((await worker.fetch(request("/manage/deals/preview", proposal, "bad"), env)).status, 401);
for (const changed of [ { sourceUrl: "https://evil.example/pledge/Packages/X" }, { sourceUrl: "https://robertsspaceindustries.com/en/comm-link/transmission/21339-X" }, { sourceUrl: "https://robertsspaceindustries.com/pledge/Standalone-Ships/Aurora" }, { imageUrl: "" }, { imageUrl: "https://evil.example/ship.jpg" }, { imageUrl: "https://robertsspaceindustries.com.evil.example/ship.png" }, { imageUrl: "javascript:alert(1)" }, { imageUrl: "https://media.robertsspaceindustries.com/page.html" }, { type: "Sonstiges Angebot" }, { oldPrice: "40" }, { referralEligible: "" }, { referralEligible: "maybe" }, { price: "58,2,4" }, { ship: "" }, { gameAccessConfirmed: false }, { extras: "" }, { validUntil: "2020-01-01T00:00:00.000Z" } ]) {
  assert.equal((await (await worker.fetch(request("/manage/deals/preview", { ...proposal, data: { ...proposal.data, ...changed } }), env)).json()).ok, false);
}
assert.equal(writes, 0);
const preview = await (await worker.fetch(request("/manage/deals/preview", proposal), env)).json();
assert.equal(preview.published, false);
assert.equal(preview.proposal[0].price, 58.24);
assert.equal(preview.proposal[0].oldPrice, 77.65);
assert.equal(preview.proposal[0].referralEligible, true);
assert.equal(preview.proposal[0].usdBeforeTax, undefined);
assert.equal(preview.proposal[0].imageUrl, picture);
assert.equal(preview.catalogChanged, true);
assert.equal(preview.expectedCatalogSha, null);
assert.equal(preview.proposal[0].contents.gameAccess, undefined);
assert.equal(preview.proposal[0].gameAccessConfirmed, true);
const duelistImage = "https://robertsspaceindustries.com/i/5a536fe5412375c5c2030c53ddce3aa37936a6ab/resize(910,512,cover,ADdPNihJzmPbNuTnFsH1DqUeqBRpXdSXVVtgJTyDDgscGKrzJuoFjReskvt6saXuoAnaUxfEHYamwgZAevTMLjULE)/source.webp";
const duelistPreview = await (await worker.fetch(request("/manage/deals/preview", { ...proposal, data: { ...proposal.data, imageUrl: duelistImage } }), env)).json();
assert.equal(duelistPreview.proposal[0].imageUrl, duelistImage);
assert.deepEqual(preview.proposal[0].contents.extras, ["3 Monate Versicherung", "Skin Blau"]);
assert.equal(preview.proposal[0].officialEndProvided, true);
const withoutEnd = await (await worker.fetch(request("/manage/deals/preview", { ...proposal, data: { ...proposal.data, validUntil: "" } }), env)).json();
assert.equal(withoutEnd.proposal[0].officialEndProvided, false);
assert.ok(Date.parse(withoutEnd.proposal[0].validUntil)-Date.parse(withoutEnd.proposal[0].checkedAt) === 7*86400000);
assert.equal(writes, 0);
assert.equal((await worker.fetch(request("/manage/deals/publish", { ...proposal, expectedSha: "stale" }), env)).status, 409);
const saved = await (await worker.fetch(request("/manage/deals/publish", { ...proposal, expectedSha: preview.expectedSha, expectedCatalogSha: preview.expectedCatalogSha }), env)).json();
assert.equal(saved.published, true);
assert.equal(saved.catalogSaved, true);
assert.equal(writes, 1);
assert.equal(catalogWrites, 1);
assert.equal(shipImages[0].imageUrl, picture);
assert.equal((await (await worker.fetch(request("/manage/deals/state"), env)).json()).shipImages[0].ship, "Aurora");
assert.equal((await (await worker.fetch(new Request("https://example.com/api/deals"), env)).json())[0].name, "Test Game Package");
const providedReferral = "https://www.robertsspaceindustries.com/enlist?referral=STAR-6KT2-XJBC";
assert.deepEqual(await (await worker.fetch(new Request("https://example.com/api/referral"), env)).json(), { enabled: true, url: providedReferral });
assert.deepEqual(await (await worker.fetch(new Request("https://example.com/api/referral"), { ...env, REFERRAL_URL: "https://robertsspaceindustries.com/enlist?referral=DEINCODE" })).json(), { enabled: true, url: providedReferral });
assert.equal((await (await worker.fetch(new Request("https://example.com/api/referral"), { ...env, REFERRAL_URL: "https://robertsspaceindustries.com/enlist?referral=ABCDE123" })).json()).enabled, true);

const app = await readFile(new URL("../public/app.js", import.meta.url), "utf8");
const context = { document: { addEventListener() {} }, Intl, Date, URL, encodeURIComponent };
vm.createContext(context); vm.runInContext(app, context);
const now = Date.now();
assert.equal(context.liveDeals(deals, now).length, 1);
assert.equal(context.liveDeals([{ ...deals[0], gameAccessConfirmed: false }], now).length, 0);
assert.equal(context.liveDeals([{ ...deals[0], imageUrl: "" }], now).length, 0);
assert.equal(context.liveDeals([{ ...deals[0], type: "Sonstiges Angebot" }], now).length, 0);
assert.equal(context.liveDeals([{ ...deals[0], contents: undefined }], now).length, 0);
assert.equal(context.isOfficialSource(providedReferral), true);
assert.equal(context.liveDeals([{ ...deals[0], checkedAt: new Date(now-6*86400000).toISOString() }], now).length, 1);
assert.equal(context.liveDeals([{ ...deals[0], checkedAt: new Date(now-8*86400000).toISOString() }], now).length, 0);
assert.equal(context.liveDeals([{ ...deals[0], validUntil: new Date(now-1).toISOString() }], now).length, 0);
assert.equal(context.liveDeals([{ ...deals[0], sourceUrl: "javascript:alert(1)" }], now).length, 0);
assert.match(context.renderDeals(deals), /Test Game Package/);
assert.match(context.renderDeals(deals), /<img src="https:\/\/media\.robertsspaceindustries\.com\/package\/aurora\.jpg\?size=large"/);
assert.match(context.renderDeals(deals), /Qualifiziert sich für Referral: <strong>Ja<\/strong>/);
assert.match(context.renderDeals([{ ...deals[0], referralEligible: false }]), /Qualifiziert sich für Referral: <strong>Nein<\/strong>/);
assert.match(context.renderDeals(deals), /58,24/);
assert.match(context.renderDeals(deals), /inklusive deutscher MwSt/);
assert.match(context.renderDeals(deals), /Skin Blau/);
assert.ok(!context.renderDeals(deals).includes("Spielzugang:"));
assert.ok(!context.renderDeals([{ ...deals[0], contents: { ...deals[0].contents, extras: ["<script>alert(1)</script>"] } }]).includes("<script>"));
assert.ok(!context.renderDeals([{ ...deals[0], name: "<script>alert(1)</script>" }]).includes("<script>"));
assert.equal((await readFile(new URL("../public/referral.html", import.meta.url), "utf8")).includes("DEINCODE"), false);
const dealPage = await readFile(new URL("../public/deals.html", import.meta.url), "utf8");
assert.match(dealPage, /RSI-Konto mit Referral erstellen/);
assert.match(dealPage, /Star-Citizen-Spielzugang/);
const variantShop = "https://robertsspaceindustries.com/pledge/Packages/Aurora-Special";
const variant = { ...proposal, data: { ...proposal.data, name: "Aurora Special Package", sourceUrl: variantShop, ship: "  aurora ", imageUrl: duelistImage, saveImageToCatalog: false } };
const variantPreview = await (await worker.fetch(request("/manage/deals/preview", variant), env)).json();
assert.equal(variantPreview.catalogChanged, false);
assert.equal((await (await worker.fetch(request("/manage/deals/publish", { ...variant, expectedSha: variantPreview.expectedSha, expectedCatalogSha: variantPreview.expectedCatalogSha }), env)).json()).published, true);
assert.equal(shipImages[0].imageUrl, picture);
assert.equal(catalogWrites, 1);
const replaceStandard = { ...variant, data: { ...variant.data, saveImageToCatalog: true } };
const replacePreview = await (await worker.fetch(request("/manage/deals/preview", replaceStandard), env)).json();
assert.equal(replacePreview.catalogChanged, true);
const knownCatalogSha = catalogSha;
catalogSha = "changed-elsewhere";
assert.equal((await worker.fetch(request("/manage/deals/publish", { ...replaceStandard, expectedSha: replacePreview.expectedSha, expectedCatalogSha: replacePreview.expectedCatalogSha }), env)).status, 409);
assert.equal(writes, 2);
catalogSha = knownCatalogSha;
const remove = { action: "remove", data: { sourceUrl: shop } };
const removePreview = await (await worker.fetch(request("/manage/deals/preview", remove), env)).json();
assert.equal(removePreview.proposal.length, 1);
assert.equal((await (await worker.fetch(request("/manage/deals/publish", { ...remove, expectedSha: removePreview.expectedSha }), env)).json()).published, true);
assert.equal(writes, 3);
assert.equal(shipImages[0].imageUrl, picture);
console.log("Deals: Bildkatalog, Sonderbild, Kommapreise, 7-Tage-Ablauf, Referral und Spielzugang: OK");
